<?php

/**
 * @file
 * Contains custom_password_policy.module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_entity_base_field_info_alter().
 */
function custom_password_policy_entity_base_field_info_alter(&$fields, EntityTypeInterface $entity_type) {
  // Only alter the user entity type.
  if ($entity_type->id() === 'user') {
    // Check if the pass field exists.
    if (isset($fields['pass']) && $fields['pass'] instanceof BaseFieldDefinition) {
      // Add the custom constraint to the pass field.
      $fields['pass']->addConstraint('PasswordPolicy', []);
    }
  }
}