<?php

declare(strict_types=1);

/**
 * @file
 * Provides a generated entity entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function generated_entity_theme(): array {
  return [
    'generated_entity' => ['render element' => 'elements'],
  ];
}

/**
 * Prepares variables for generated entity templates.
 *
 * Default template: generated-entity.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the generated entity information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_generated_entity(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

